ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG FAST_BUILD=false
ARG MAKEFLAGS=-j8
ENV MAKEFLAGS=$MAKEFLAGS \
        ERL="erl"

USER otptest
RUN exec 2>&1 && \
    ./otp_build autoconf && \
    ./configure $CONFIG_FLAGS && \
    make && \
    make release RELEASE_ROOT=$install_dir

RUN ${FAST_BUILD} \
    || (exec 2>&1 && \
    	make docs && \
    	make release_docs RELEASE_ROOT=$install_dir)

#
# Check that install/release isn't totally broken
# by installing/releasing as another user...
USER otp
RUN exec 2>&1 && \
    make release RELEASE_ROOT=/daily_build/check_install && \
    ( ${FAST_BUILD} \
      || make release_docs RELEASE_ROOT=/daily_build/check_install ) && \
    rm -rf /daily_build/check_install

USER otptest

WORKDIR $install_dir
RUN ./Install -minimal $install_dir

WORKDIR /daily_build
ENV PATH=$install_dir/bin:$ERL_TOP/bin:$PATH
